/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_resonance_cashdisplay_uart_SerialPort */

#ifndef _Included_com_resonance_cashdisplay_uart_SerialPort
#define _Included_com_resonance_cashdisplay_uart_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_resonance_cashdisplay_uart_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;IIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_resonance_cashdisplay_uart_SerialPort_open
        (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_resonance_cashdisplay_uart_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_resonance_cashdisplay_uart_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_resonance_cashdisplay_uart_SerialPort_Builder */

#ifndef _Included_com_resonance_cashdisplay_uart_SerialPort_Builder
#define _Included_com_resonance_cashdisplay_uart_SerialPort_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
